apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
metadata:
    name: eksutils-deployment
    namespace: default
    labels: 
      app: toolbox
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: toolbox
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: toolbox
    spec:
      containers:
      - name: eksutils
        image: allamand/eksutils:latest
        imagePullPolicy: Always
        command:
          - tail
          - -f
          - /dev/null
    #  - env:
    #    - name: WORDPRESS_DATABASE_PASSWORD
    #      valueFrom:
    #        secretKeyRef:
    #          key: mariadb-password
    #          name: wordpress-rds-externaldb
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 300m
            memory: 512Mi
#        volumeMounts:
#        - mountPath: /bitnami/wordpress
#          name: wordpress-data
#          subPath: wordpress
#          readOnly: true
      enableServiceLinks: true
      restartPolicy: Always
      schedulerName: default-scheduler
#To work with other username
#      securityContext:
#        fsGroup: 1001
#        runAsUser: 1001
      serviceAccount: default
      serviceAccountName: k8s-101-role
      terminationGracePeriodSeconds: 0
    #  volumes:
    #  - name: wordpress-data
    #    persistentVolumeClaim:
    #      claimName: wordpress-rds
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-101-role
subjects:
- kind: ServiceAccount
  name: k8s-101-role
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-101-role
  namespace: default
